[package]
name = "vdesigner-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
image.workspace = true
serde.workspace = true
serde_json = "1"
thiserror.workspace = true
webp.workspace = true
ravif.workspace = true
rgb.workspace = true
fast_image_resize.workspace = true
imageproc.workspace = true
resvg.workspace = true
